# Generated by Django 6.0.5 on 2026-05-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
