# Generated by Django 6.0.5 on 2026-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_linkmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='link',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
